apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashufinal-deploy
  name: ashufinal-deploy
  namespace: ashu-project # add this line 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ashufinal-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ashufinal-deploy
    spec:
      containers:
      - image: dockerashu/ashuhcl:appfinal
        name: ashuhcl
        ports:
        - containerPort: 80
        imagePullPolicy: Always 
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashufinal-deploy
  name: ashulb1234
  namespace: ashu-project # add this line 
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ashufinal-deploy
  type: NodePort
status:
  loadBalancer: {}

